services:
  - type: web
    name: solvix-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SOLVIX_CORS_ALLOWED_ORIGIN
        sync: false
      - key: SOLVIX_JWT_SECRET
        sync: false
      - key: SOLVIX_CUSTOMER_USERNAME
        sync: false
      - key: SOLVIX_CUSTOMER_PASSWORD
        sync: false
      - key: SOLVIX_SUPPORT_USERNAME
        sync: false
      - key: SOLVIX_SUPPORT_PASSWORD
        sync: false
