ALTER TABLE ticket_comments RENAME TO ticket_comments_legacy;

CREATE TABLE ticket_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    ticket_id UUID NOT NULL,
    body VARCHAR(4000) NOT NULL,
    author VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_ticket_comments PRIMARY KEY (id),
    CONSTRAINT fk_ticket_comments_ticket_v4
        FOREIGN KEY (ticket_id) REFERENCES tickets (id)
);

INSERT INTO ticket_comments (ticket_id, body, author, created_at)
SELECT ticket_id, comment, 'legacy', CURRENT_TIMESTAMP
FROM ticket_comments_legacy;

DROP TABLE ticket_comments_legacy;

CREATE INDEX idx_ticket_comments_ticket_created
    ON ticket_comments (ticket_id, created_at, id);
