solvix.security.auth0.issuer-uri=${AUTH0_ISSUER_URI}
solvix.security.auth0.jwk-set-uri=${AUTH0_JWK_SET_URI:${AUTH0_ISSUER_URI}.well-known/jwks.json}
solvix.security.auth0.audience=${AUTH0_API_AUDIENCE}
solvix.security.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
