solvix.security.cognito.issuer-uri=${COGNITO_ISSUER_URI}
solvix.security.cognito.jwk-set-uri=${COGNITO_JWK_SET_URI:${COGNITO_ISSUER_URI}/.well-known/jwks.json}
solvix.security.cognito.client-id=${COGNITO_CLIENT_ID}
solvix.security.cors.allowed-origin=${CORS_ALLOWED_ORIGIN}
